"""added log table

Revision ID: 1fdba7cac41a
Revises: 1856e8cfd8d6
Create Date: 2017-01-25 16:14:55.535413

"""

# revision identifiers, used by Alembic.
revision = '1fdba7cac41a'
down_revision = '1856e8cfd8d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('trace', sa.String(), nullable=True),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    ### end Alembic commands ###
