"""extended option table

Revision ID: 73f275f80e1e
Revises: 1fdba7cac41a
Create Date: 2017-01-25 19:17:32.690133

"""

# revision identifiers, used by Alembic.
revision = '73f275f80e1e'
down_revision = '1fdba7cac41a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('option', 'option_orig')
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('wizlock', sa.Boolean(), nullable=True),
    sa.Column('debug', sa.Boolean(), nullable=True),
    sa.Column('specials', sa.Boolean(), nullable=True),
    sa.Column('pidfile', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('INSERT INTO option(id, date_created, version, port, wizlock) SELECT id, date_created, version, port, wizlock FROM option_orig')
    op.drop_table('option_orig')

    # SQLite doesn't handle adding constraints outside of table creation.
    # SQLite also doesn't do SELECT INTO

    #op.add_column('option', sa.Column('debug', sa.Boolean(), nullable=True))
    #op.add_column('option', sa.Column('specials', sa.Boolean(), nullable=True))
    #op.add_column('option', sa.Column('pidfile', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'pidfile')
    op.drop_column('option', 'specials')
    op.drop_column('option', 'debug')
    ### end Alembic commands ###
