#!/bin/sh
touch verifyit
while [ -r verifyit ]; do
  echo Ping
  sed "s/NAME/`randline $HOME/.tf/cool/words`/" <$HOME/.tf/cool/bug.master >$HOME/.tf/cool/bug.it 2>/dev/null
  tf -n -f$HOME/.tf/cool/bug.it >>verifyit 2>&1
done
