#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          wiley
# Required-Start:    $network $local_fs $remote_fs $syslog $named $time #postgresql
# Required-Stop:     $network $local_fs $remote_fs $syslog $named $time #postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init-Script for WileyMUD
### END INIT INFO
#

PORT=3000
MUDDIR=/home/wiley
MUDUSER=wiley
MUDGROUP=wiley
PATH=$MUDDIR/bin:/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=$MUDDIR/bin/wileymud
SCRIPT=$MUDDIR/bin/wileyloop
PIDFILE=$MUDDIR/etc/wileymud.pid
STARTDIR=$MUDDIR/bin
LOGFILE=`/bin/date "+$MUDDIR/lib/log/runlog.%y%m%d-%H%M%S"`
export LANG="en_US.utf8"
export LC_ALL="en_US.utf8"

test -x $DAEMON || exit 0

case "$1" in
  start)
	echo -n "Starting MUD Server: WileyMUD"
        if start-stop-daemon --quiet --stop --signal 0 --pidfile $PIDFILE --name wileymud --user $MUDUSER
	then
		echo " already running."
		exit
	fi
	/sbin/start-stop-daemon --start --quiet --chuid $MUDUSER:$MUDGROUP --chdir $STARTDIR --background --pidfile $PIDFILE --exec $SCRIPT -- -P $PIDFILE -L $LOGFILE $PORT
	echo "."
        $0 status
	;;
  stop)
	echo -n "Stopping MUD Server: WileyMUD"
	if start-stop-daemon --quiet --stop --signal 0 --pidfile $PIDFILE --name wileymud --user $MUDUSER
	then
		PID=`cat $PIDFILE`
		start-stop-daemon --quiet --stop --signal INT --user wiley --exec $DAEMON --pidfile $PIDFILE --name wileymud
		# Now we wait for it to die
		while kill -0 $PID 2>/dev/null; do sleep 1; done
		rm -f $PIDFILE
		echo "."
	else
		echo " not running.";
	fi
	;;
  restart)
	$0 stop
	$0 start
	;;
  status)
        #wiley     2037  0.0  0.0   7856  2144 ?        S    Aug01   0:00 /bin/bash /home/wiley/bin/wileyloop -P /home/wiley/etc/wileymud.pid -L /home/wiley/lib/log/runlog.180801-041043 3000
        #wiley     2041  0.2  0.1  28536 17556 ?        S    Aug01   7:12 /home/wiley/bin/wileymud -P /home/wiley/etc/wileymud.pid -L /home/wiley/lib/log/runlog.180801-041043 3000
        HEADER=`ps -auxwwww | head -1`
        DRIVER=`ps -auxwwww | grep "$DAEMON" | grep -v "grep $DAEMON" | head -1`
        LOOPER=`ps -auxwwww | grep "$SCRIPT" | grep -v "grep $SCRIPT" | head -1`
        D_PID=`echo $DRIVER | awk '{print $2}'`
        D_PORT=`echo $DRIVER | awk '{print $NF}'`
        L_PID=`echo $LOOPER | awk '{print $2}'`

        if [ -n "$D_PID" ]; then
            D_RUNNING="The driver is running on port $D_PORT"
        else
            D_RUNNING="The driver is not running, but is configured to use port $PORT"
        fi

        if [ -n "$D_PID" ]; then
            L_RUNNING="The loop script is running."
        else
            L_RUNNING="The loop script is not running."
        fi

        echo ""
        if [ -n "$D_PID" -o -n "$L_PID" ]; then
            echo "$HEADER"
            echo "$DRIVER"
            echo "$LOOPER"
            echo ""
        fi
        echo "$D_RUNNING"
        echo "$L_RUNNING"
        echo ""
	;;
  *)
	echo "Usage: /etc/init.d/wiley {start|stop|restart|status}"
	exit 1
esac

exit 0
