/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /home/horse/u0/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp Locker: vern $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif	/* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "dbparser.l"
#define INITIAL 0
# line 2 "dbparser.l"
#define TOK_zero		0
#define TOK_inherit		1
#define TOK_pound		2
#define TOK_end			3
#define TOK_name		4
#define TOK_desc		5
#define TOK_sdesc		6
#define TOK_sect		7
#define TOK_zone		8
#define TOK_flags		9
#define TOK_type		10
#define TOK_exit		11
#define TOK_key			12
#define TOK_goto		13
#define TOK_dark		14
#define TOK_no_mob		15
#define TOK_indoors		16
#define TOK_no_fight		17
#define TOK_no_steal		18
#define TOK_no_summon		19
#define TOK_no_magic		20
#define TOK_private		21
#define TOK_sound1		22
#define TOK_sound2		23
#define TOK_isdoor		24
#define TOK_closed		25
#define TOK_locked		26
#define TOK_secret		27
#define TOK_trapped		28
#define TOK_pickproof		29
#define TOK_inside		30
#define TOK_city		31
#define TOK_field		32
#define TOK_forest		33
#define TOK_hills		34
#define TOK_mountain		35
#define TOK_swim		36
#define TOK_no_swim		37
#define TOK_air			38
#define TOK_underwater		39
#define TOK_north		40
#define TOK_east		41
#define TOK_south		42
#define TOK_west		43	
#define TOK_up			44
#define TOK_down		45
#define TOK_tilde		46
#define TOK_ID			47
#define TOK_cr			48
#define TOK_int			49
#define TOK_elof		50
#define TOK_tele_time		51
#define TOK_tele_targ		52
#define TOK_tele_look		53
#define TOK_no			54
#define TOK_yes			55
#define TOK_off			56
#define TOK_on			57
#define TOK_ex_desc		58

int ROOMcompile = 0;
int LINEcount = 1;
int NESTlevel = 0;
int MYtoken;

struct RET_flags {
  int TOKEN_type;
  int BIT_flag;
} GLOBAL_flags;


int LIST_sector[] = 
{ 
  TOK_inside,
  TOK_city,
  TOK_field,
  TOK_forest,
  TOK_hills,
  TOK_mountain,
  TOK_swim,
  TOK_no_swim,
  TOK_air,
  TOK_underwater,
  -1,
};

char * Sector_names[] = 
{
  "inside",
  "city",
  "field",
  "forest",
  "hills",
  "mountain",
  "swim",
  "no swim",
  "air",
  "underwater",
  0,
};

int LIST_water[] =
{
  TOK_swim,
  TOK_no_swim,
  TOK_air,
  TOK_underwater,
  -1,
};

int LIST_direction[] =
{
  TOK_north,
  TOK_east,
  TOK_south,
  TOK_west,
  TOK_up,
  TOK_down,
  -1,
};

int LIST_reply[] =
{
  TOK_yes,
  TOK_no,
  -1,
};

int LIST_exit_flags[] =
{
  TOK_isdoor,
  TOK_closed,
  TOK_locked,
  TOK_secret,
  TOK_trapped,
  TOK_pickproof,
  -1,
};

char * EXIT_FLAGS_NAMES[] = 
{
  "Isdoor",
  "Closed",
  "Locked",
  "Secret",
  "Trapped",
  "PickProof",
  "\n",
};
int EXIT_FLAGS[] = {1,2,4,8,16,32,-1};

# line 156 "dbparser.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 64
typedef int yy_state_type;
static const short int yy_accept[238] =
    {   0,
        0,    0,   64,   62,   61,   60,    5,   62,    1,    3,
        2,    4,   59,   59,   59,   48,   45,   59,   59,   59,
       59,   59,   59,   59,   43,   59,   59,   44,   59,   47,
       46,   59,   59,   49,   50,    1,    3,    2,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   54,
       59,   57,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   47,   59,   59,   59,   41,   59,   59,   59,
       59,   59,   59,    6,    0,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   15,   59,   59,   59,    0,   59,

       56,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   55,   59,   34,   59,   17,    8,   48,   45,
        0,   14,   59,   59,   59,   16,   59,   59,   59,   59,
       59,   59,    7,    0,    0,    0,   59,   59,   59,   59,
       59,   10,   59,   59,   39,   59,   59,   13,   59,   46,
       11,   59,    8,    0,   35,   12,   59,   37,   59,   59,
       59,   59,   59,    7,    0,    0,    0,    0,    0,    0,
       43,   59,   59,    9,   59,   59,   44,    0,   59,   59,
       28,    0,   36,   59,   33,   27,   29,   59,    0,    0,
       18,    0,    0,    0,   59,   59,    9,   30,   25,   26,

        0,    0,   59,   59,   58,   19,   59,    0,    0,    0,
        0,   40,   59,   24,    0,    0,    0,   31,   59,   38,
       20,   23,   21,    0,   59,    0,    0,    0,   59,   22,
       32,   53,   52,   51,   59,   42,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    1,    7,    8,    9,   10,
        8,    8,    8,    8,    8,    8,    8,   11,   12,    1,
        1,   13,    1,   14,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       25,   32,   33,   34,   35,   36,   37,   38,   39,   40,
        1,    1,    1,    1,   15,    1,   16,   17,   18,   19,

       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   25,   32,   33,   34,   35,   36,   37,   38,
       39,   40,    1,    1,    1,   41,    1
    } ;

static const YY_CHAR yy_meta[42] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1
    } ;

static const short int yy_base[241] =
    {   0,
        0,    0,  252,  253,  253,  253,  253,  238,   34,    0,
        0,  253,  226,    0,   21,   30,   33,   27,  219,  224,
       23,  227,  216,  215,   31,   34,   34,   45,   47,   39,
      224,  223,  212,  253,  253,   64,    0,    0,    0,  209,
      206,  209,  206,  204,  199,  202,  215,   54,  213,  216,
      199,  196,  202,   57,  209,  188,  208,  190,  196,   62,
      202,    0,  204,  197,  200,  201,  183,  193,  189,  199,
      183,  194,    0,  179,  178,  181,    0,  170,  175,  181,
      188,  176,  170,    0,  184,  168,  174,  178,  179,  168,
      170,  166,  171,  164,    0,  167,  163,  171,   59,  156,

        0,  163,  152,  154,   49,   55,  158,  165,  153,  163,
      162,  147,    0,  160,    0,  159,    0,   92,    0,    0,
      158,    0,  158,  143,  142,    0,  141,  143,  153,  141,
      150,  135,  164,  143,   69,   63,  143,  134,  148,  145,
      142,    0,  142,  137,    0,  144,  127,    0,  125,    0,
        0,  137,  253,  122,    0,    0,  120,    0,  121,  132,
      119,  131,  133,  253,  126,  125,  129,  125,  116,  119,
        0,  110,  107,  136,  105,   92,    0,   76,  118,  100,
        0,  118,    0,  102,    0,    0,    0,  110,  110,  108,
      253,  115,  102,  101,   98,  107,  253,    0,    0,    0,

       96,   88,  106,  108,  253,    0,   94,   88,  103,   93,
       89,  253,   87,    0,   84,   79,   81,    0,   74,    0,
      253,  253,  253,   78,   85,   79,   71,   71,   68,  253,
        0,  253,  253,  253,   27,    0,  253,  112,  115,   50
    } ;

static const short int yy_def[241] =
    {   0,
      237,    1,  237,  237,  237,  237,  237,  237,  237,  238,
      239,  237,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  237,  237,  237,  238,  239,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  237,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  237,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      237,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  237,  237,  237,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  237,  237,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  237,  237,  237,  237,  237,  237,  237,
      240,  240,  240,  240,  240,  240,  240,  237,  240,  240,
      240,  237,  240,  240,  240,  240,  240,  240,  237,  237,
      237,  237,  237,  237,  240,  240,  237,  240,  240,  240,

      237,  237,  240,  240,  237,  240,  240,  237,  237,  237,
      237,  237,  240,  240,  237,  237,  237,  240,  240,  240,
      237,  237,  237,  237,  240,  237,  237,  237,  240,  237,
      240,  237,  237,  237,  240,  240,    0,  237,  237,  237
    } ;

static const short int yy_nxt[295] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,    9,    9,
       10,   11,    4,   12,    4,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   14,   22,   23,   24,   25,   26,
       27,   14,   28,   29,   30,   14,   31,   14,   32,   33,
       34,   36,   36,   36,   41,   43,   59,   42,   46,   44,
       49,   54,   39,   50,   61,   55,   51,   63,  236,   45,
       60,   47,   62,   65,   66,   64,   69,   72,   85,   73,
       48,   36,   36,   36,   67,   92,   99,   86,   70,  134,
      141,   68,  142,  143,  166,   71,  135,  235,  144,   93,
      234,  136,  233,  100,  153,  153,  168,  169,  167,  170,

      199,  200,  201,  216,  232,  231,  230,  229,  228,  202,
      227,  217,   37,  226,   37,   38,  225,   38,  224,  223,
      222,  221,  220,  219,  218,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  152,  151,
      150,  149,  148,  147,  146,  145,  140,  139,  138,  137,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,

      123,  122,  121,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  106,  105,  104,
      103,  102,  101,   98,   97,   96,   95,   94,   91,   90,
       89,   88,   87,   84,   83,   82,   81,   80,   79,   78,
       77,   76,   75,   74,   58,   57,   56,   53,   52,   40,
       35,  237,    3,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237

    } ;

static const short int yy_chk[295] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,    9,    9,   15,   16,   25,   15,   17,   16,
       18,   21,  240,   18,   26,   21,   18,   27,  235,   16,
       25,   17,   26,   28,   28,   27,   29,   30,   48,   30,
       17,   36,   36,   36,   28,   54,   60,   48,   29,   99,
      105,   28,  105,  106,  135,   29,   99,  229,  106,   54,
      228,   99,  227,   60,  118,  118,  136,  136,  135,  136,

      176,  176,  178,  202,  226,  225,  224,  219,  217,  178,
      216,  202,  238,  215,  238,  239,  213,  239,  211,  210,
      209,  208,  207,  204,  203,  201,  196,  195,  194,  193,
      192,  190,  189,  188,  184,  182,  180,  179,  175,  174,
      173,  172,  170,  169,  168,  167,  166,  165,  163,  162,
      161,  160,  159,  157,  154,  152,  149,  147,  146,  144,
      143,  141,  140,  139,  138,  137,  134,  133,  132,  131,
      130,  129,  128,  127,  125,  124,  123,  121,  116,  114,
      112,  111,  110,  109,  108,  107,  104,  103,  102,  100,
       98,   97,   96,   94,   93,   92,   91,   90,   89,   88,

       87,   86,   85,   83,   82,   81,   80,   79,   78,   76,
       75,   74,   72,   71,   70,   69,   68,   67,   66,   65,
       64,   63,   61,   59,   58,   57,   56,   55,   53,   52,
       51,   50,   49,   47,   46,   45,   44,   43,   42,   41,
       40,   33,   32,   31,   24,   23,   22,   20,   19,   13,
        8,    3,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237

    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;



    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 238 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 237 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 157 "dbparser.l"
{ return(TOK_int); }
	YY_BREAK
case 2:
# line 158 "dbparser.l"
{ printf("%s\n",yytext); }
	YY_BREAK
case 3:
# line 159 "dbparser.l"
{ }
	YY_BREAK
case 4:
# line 160 "dbparser.l"
{ return(TOK_inherit); }
	YY_BREAK
case 5:
# line 161 "dbparser.l"
{ NESTlevel = 1;return(TOK_pound); }
	YY_BREAK
case 6:
# line 162 "dbparser.l"
{ NESTlevel--;return(TOK_end); }
	YY_BREAK
case 7:
# line 163 "dbparser.l"
{ return(TOK_name); }
	YY_BREAK
case 8:
# line 164 "dbparser.l"
{ return(TOK_desc); }
	YY_BREAK
case 9:
# line 165 "dbparser.l"
{ return(TOK_sdesc); }
	YY_BREAK
case 10:
# line 166 "dbparser.l"
{ return(TOK_sect); }
	YY_BREAK
case 11:
# line 167 "dbparser.l"
{ return(TOK_zone); }
	YY_BREAK
case 12:
# line 168 "dbparser.l"
{ return(TOK_flags); }
	YY_BREAK
case 13:
# line 169 "dbparser.l"
{ return(TOK_type); }
	YY_BREAK
case 14:
# line 170 "dbparser.l"
{ NESTlevel++;return(TOK_exit); }
	YY_BREAK
case 15:
# line 171 "dbparser.l"
{ return(TOK_key); }
	YY_BREAK
case 16:
# line 172 "dbparser.l"
{ return(TOK_goto); }
	YY_BREAK
case 17:
# line 173 "dbparser.l"
{ return(TOK_dark); }
	YY_BREAK
case 18:
# line 174 "dbparser.l"
{ return(TOK_no_mob); }
	YY_BREAK
case 19:
# line 175 "dbparser.l"
{ return(TOK_indoors); }
	YY_BREAK
case 20:
# line 176 "dbparser.l"
{ return(TOK_no_fight); }
	YY_BREAK
case 21:
# line 177 "dbparser.l"
{ return(TOK_no_steal); }
	YY_BREAK
case 22:
# line 178 "dbparser.l"
{ return(TOK_no_summon) ; }
	YY_BREAK
case 23:
# line 179 "dbparser.l"
{ return(TOK_no_magic); }
	YY_BREAK
case 24:
# line 180 "dbparser.l"
{ return(TOK_private); }
	YY_BREAK
case 25:
# line 181 "dbparser.l"
{ LINEcount++;return(TOK_sound1); }
	YY_BREAK
case 26:
# line 182 "dbparser.l"
{ LINEcount++;return(TOK_sound2); }
	YY_BREAK
case 27:
# line 183 "dbparser.l"
{ return(TOK_isdoor); }
	YY_BREAK
case 28:
# line 184 "dbparser.l"
{ return(TOK_closed); }
	YY_BREAK
case 29:
# line 185 "dbparser.l"
{ return(TOK_locked); }
	YY_BREAK
case 30:
# line 186 "dbparser.l"
{ return(TOK_secret); }
	YY_BREAK
case 31:
# line 187 "dbparser.l"
{ return(TOK_trapped); }
	YY_BREAK
case 32:
# line 188 "dbparser.l"
{ return(TOK_pickproof); }
	YY_BREAK
case 33:
# line 189 "dbparser.l"
{ return(TOK_inside); }
	YY_BREAK
case 34:
# line 190 "dbparser.l"
{ return(TOK_city); }
	YY_BREAK
case 35:
# line 191 "dbparser.l"
{ return(TOK_field); }
	YY_BREAK
case 36:
# line 192 "dbparser.l"
{ return(TOK_forest); }
	YY_BREAK
case 37:
# line 193 "dbparser.l"
{ return(TOK_hills); }
	YY_BREAK
case 38:
# line 194 "dbparser.l"
{ return(TOK_mountain); }
	YY_BREAK
case 39:
# line 195 "dbparser.l"
{ return(TOK_swim); }
	YY_BREAK
case 40:
# line 196 "dbparser.l"
{ return(TOK_no_swim); }
	YY_BREAK
case 41:
# line 197 "dbparser.l"
{ return(TOK_air); }
	YY_BREAK
case 42:
# line 198 "dbparser.l"
{ return(TOK_underwater); }
	YY_BREAK
case 43:
# line 199 "dbparser.l"
{ return(TOK_north); }
	YY_BREAK
case 44:
# line 200 "dbparser.l"
{ return(TOK_south); }
	YY_BREAK
case 45:
# line 201 "dbparser.l"
{ return(TOK_east); }
	YY_BREAK
case 46:
# line 202 "dbparser.l"
{ return(TOK_west); }
	YY_BREAK
case 47:
# line 203 "dbparser.l"
{ return(TOK_up); }
	YY_BREAK
case 48:
# line 204 "dbparser.l"
{ return(TOK_down); }
	YY_BREAK
case 49:
# line 205 "dbparser.l"
{ return(TOK_tilde); }
	YY_BREAK
case 50:
# line 206 "dbparser.l"
{ return(TOK_elof); }
	YY_BREAK
case 51:
# line 207 "dbparser.l"
{ return(TOK_tele_time); }
	YY_BREAK
case 52:
# line 208 "dbparser.l"
{ return(TOK_tele_targ); }
	YY_BREAK
case 53:
# line 209 "dbparser.l"
{ return(TOK_tele_look); }
	YY_BREAK
case 54:
# line 210 "dbparser.l"
{ return(TOK_no); }
	YY_BREAK
case 55:
# line 211 "dbparser.l"
{ return(TOK_yes); }
	YY_BREAK
case 56:
# line 212 "dbparser.l"
{ return(TOK_off); }
	YY_BREAK
case 57:
# line 213 "dbparser.l"
{ return(TOK_on); }
	YY_BREAK
case 58:
# line 214 "dbparser.l"
{ return(TOK_ex_desc); }
	YY_BREAK
case 59:
# line 215 "dbparser.l"
{ return(TOK_ID); }
	YY_BREAK
case 60:
# line 216 "dbparser.l"
{ LINEcount++;}  
	YY_BREAK
case 61:
# line 217 "dbparser.l"
{ }
	YY_BREAK
case 62:
# line 218 "dbparser.l"
{ }
	YY_BREAK
case 63:
# line 219 "dbparser.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 238 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 238 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 237);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 219 "dbparser.l"

