#define err_s		58	/*
				 * this should be the last token we parse 
				 */
#define ERR_inherit_not_found (err_s+1)
#define ERR_seq		(err_s+2)
#define ERR_strlen	(err_s+3)
#define ERR_unknown	(err_s+4)
#define ERR_ex_name	(err_s+5)
#define ERR_list	(err_s+6)

char                            *error_list[] =
{
  "EOF found on file before done.",
  "error with inherit.",
  "error with pound '#'.",
  "error with end statement.",
  "error with name statement.",
  "error with desc statement.",
  "error with short desc statement.",
  "error with sect statement.",
  "error with zone statement.",
  "error with flags statement.",
  "error with type statement.",
  "error with exit statement.",
  "error with key statement.",
  "error with goto statement.",
  "error with dark statement.",
  "error with no_mob statement.",
  "error with indoors statement.",
  "error with no_fight statement.",
  "error with no_steal statement.",
  "error with no_summon statement.",
  "error with no_magic statement.",
  "error with private statement.",
  "error with sound1 statement.",
  "error with sound2 statement.",
  "error with isdoor statement.",
  "error with closed statement.",
  "error with locked statement.",
  "error with secret statement.",
  "error with trapped statement.",
  "error with pick proof statement.",
  "error with inside statement.",
  "error with city statement.",
  "error with field statement.",
  "error with forest statement.",
  "error with hills statement.",
  "error with mountain statement.",
  "error with swim statement.",
  "error with no_swim statement.",
  "error with air statement.",
  "error with underwater statement.",
  "error with north statement.",
  "error with east statement.",
  "error with south statement.",
  "error with west statement.",
  "error with up statement.",
  "error with down statement.",
  "error with tilde statement.",
  "error with ID (string?).",
  "error with cr?",
  "error with integer value.",
  "error with element of '->' statement.",
  "error with teleport time statement.",
  "error with teleport target statement.",
  "error with teleport look statement ( use YES,yes,NO,no )",
  "error with NO response.",
  "error with YES response.",
  "error with OFF response.",
  "error with ON response.",
  "error with extra description statement.",

  "error with inheriting room, not found in dbase?",
  "error with rooms being out of sequence!",
  "error, string is too long.",
"Hey, I can only catch most of them, I have no clue as to this one.",
  "error, no key name given for extra description.",
  "error, keyword not found in list of usable values.",
};
