/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/flex-2.4.7/RCS/flex.skl,v 1.2 94/08/03 11:13:24 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define YY_START ((yy_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#ifdef __cplusplus
extern "C" {
#endif
	extern int yywrap YY_PROTO(( void ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static void yyunput YY_PROTO(( int c, char *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
static void yy_push_state YY_PROTO(( int new_state ));
static void yy_pop_state YY_PROTO(( void ));
static int yy_top_state YY_PROTO(( void ));

static void *yy_flex_alloc YY_PROTO(( unsigned int ));
static void *yy_flex_realloc YY_PROTO(( void *, unsigned int ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define INITIAL 0
typedef unsigned char YY_CHAR;
typedef int yy_state_type;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
extern char *yytext;
#define yytext_ptr yytext

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, const char *, int ));
#endif

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_END_OF_BUFFER 64
static const short int yy_accept[249] =
    {   0,
        0,    0,   64,   62,   61,   60,    5,   62,    1,    3,
        2,    4,   59,   48,   45,   43,   59,   44,   47,   46,
       59,   59,   59,   48,   45,   59,   59,   59,   59,   59,
       59,   59,   43,   59,   59,   44,   59,   47,   46,   59,
       59,   49,   50,    1,    3,    2,   59,   54,   59,   57,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   54,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   47,   59,   59,   59,   56,   55,   41,
       59,   59,   59,   59,   59,   59,    6,    0,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   15,   59,   59,
       59,    0,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   34,   59,   17,    8,   48,
       45,    0,   14,   59,   59,   59,   16,   59,   59,   59,
       59,   59,   59,    7,    0,    0,    0,   59,   59,   59,
       59,   59,   10,   59,   59,   39,   59,   59,   13,   59,
       46,   11,   59,    8,    0,   35,   12,   59,   37,   59,
       59,   59,   59,   59,    7,    0,    0,    0,    0,    0,
        0,   43,   59,   59,    9,   59,   59,   44,    0,   59,
       59,   28,    0,   36,   59,   33,   27,   29,   59,    0,

        0,   18,    0,    0,    0,   59,   59,    9,   30,   25,
       26,    0,    0,   59,   59,   58,   19,   59,    0,    0,
        0,    0,   40,   59,   24,    0,    0,    0,   31,   59,
       38,   20,   23,   21,    0,   59,    0,    0,    0,   59,
       22,   32,   53,   52,   51,   59,   42,    0
    } ;

static const int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    1,    7,    8,    9,   10,
        8,    8,    8,    8,    8,    8,    8,   11,   12,    1,
        1,   13,    1,   14,   15,   15,   15,   16,   17,   18,
       15,   15,   15,   15,   15,   15,   15,   19,   20,   15,
       15,   15,   21,   15,   22,   15,   23,   15,   24,   15,
        1,    1,    1,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   15,   35,   36,   37,   38,
       39,   40,   15,   41,   42,   43,   44,   45,   46,   47,
       48,   49,    1,    1,    1,   50,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int yy_meta[51] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1
    } ;

static const short int yy_base[252] =
    {   0,
        0,    0,  267,  268,  268,  268,  268,  253,   43,    0,
        0,  268,    0,    0,    0,  245,   36,    0,    0,    0,
      247,  229,   22,   31,   33,   26,  223,  227,   25,  230,
      220,  219,   38,   35,   34,   49,   42,   36,  227,  226,
      216,  268,  268,   76,    0,    0,    0,    0,  236,    0,
      232,  211,  208,  211,  208,  206,  201,  204,  216,   57,
      214,  217,  201,  198,  204,   52,  210,  190,  209,  192,
      198,   62,  203,  205,  198,  201,  202,  185,  194,  191,
      200,  185,  195,    0,  181,  180,  183,    0,    0,    0,
      172,  177,  183,  189,  178,  172,    0,  185,  170,  176,

      179,  180,  170,  172,  168,  172,  166,    0,  169,  165,
      172,   62,  158,  165,  154,  156,   55,   54,  160,  166,
      155,  164,  163,  149,  161,    0,  160,    0,   97,    0,
        0,  159,    0,  159,  145,  144,    0,  143,  145,  154,
      143,  151,  137,  175,  144,   63,   62,  144,  136,  149,
      146,  143,    0,  143,  138,    0,  145,  129,    0,  127,
        0,    0,  138,  268,  124,    0,    0,  122,    0,  123,
      133,  121,  132,  134,  268,  127,  126,  130,  126,  118,
      120,    0,  112,  109,  147,  107,  100,    0,   71,  119,
      102,    0,  119,    0,  104,    0,    0,    0,  111,  111,

      109,  268,  116,  104,  103,  100,  108,  268,    0,    0,
        0,   98,   85,  107,  109,  268,    0,   96,   90,  104,
       95,   91,  268,   90,    0,   89,   86,   89,    0,   81,
        0,  268,  268,  268,   83,   87,   82,   84,   85,   83,
      268,    0,  268,  268,  268,   71,    0,  268,  119,  122,
       66
    } ;

static const short int yy_def[252] =
    {   0,
      248,    1,  248,  248,  248,  248,  248,  248,  248,  249,
      250,  248,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  248,  248,  248,  249,  250,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  248,  251,  251,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  248,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  248,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  248,  248,  248,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  248,  248,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  248,  248,  248,  248,  248,  248,
      248,  251,  251,  251,  251,  251,  251,  251,  248,  251,
      251,  251,  248,  251,  251,  251,  251,  251,  251,  248,

      248,  248,  248,  248,  248,  251,  251,  248,  251,  251,
      251,  248,  248,  251,  251,  248,  251,  251,  248,  248,
      248,  248,  248,  251,  251,  248,  248,  248,  251,  251,
      251,  248,  248,  248,  248,  251,  248,  248,  248,  251,
      248,  251,  248,  248,  248,  251,  251,    0,  248,  248,
      248
    } ;

static const short int yy_nxt[319] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,    9,    9,
       10,   11,    4,   12,   13,   14,   15,   13,   16,   17,
       18,   19,   20,   21,    4,   22,   13,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       13,   36,   37,   38,   13,   39,   13,   40,   41,   42,
       44,   44,   44,   49,   50,   53,   55,   54,   58,   61,
       56,   62,   66,   71,   63,   73,   67,   74,   47,   57,
       59,   80,   50,   83,   75,   84,   72,   76,   77,   60,
      105,   98,   81,   44,   44,   44,  112,   78,  177,   82,
       99,  154,  145,  106,   79,  152,  155,  153,  146,  164,

      164,  178,  113,  147,  179,  180,  212,  181,  210,  211,
      227,  247,  246,  213,  245,  244,  243,  242,  228,   45,
      241,   45,   46,  240,   46,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  163,
      162,  161,  160,  159,  158,  157,  156,  151,  150,  149,

      148,  144,  143,  142,  141,  140,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  129,  128,  127,  126,
      125,   89,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,   88,  111,  110,  109,  108,  107,  104,
      103,  102,  101,  100,   97,   96,   95,   94,   93,   92,
       91,   90,   89,   88,   87,   86,   85,   70,   69,   68,
       65,   64,   52,   51,   48,   43,  248,    3,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248
    } ;

static const short int yy_chk[319] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        9,    9,    9,   17,   17,   23,   24,   23,   25,   26,
       24,   26,   29,   33,   26,   34,   29,   35,  251,   24,
       25,   37,   34,   38,   35,   38,   33,   36,   36,   25,
       66,   60,   37,   44,   44,   44,   72,   36,  146,   37,
       60,  118,  112,   66,   36,  117,  118,  117,  112,  129,

      129,  146,   72,  112,  147,  147,  189,  147,  187,  187,
      213,  246,  240,  189,  239,  238,  237,  236,  213,  249,
      235,  249,  250,  230,  250,  228,  227,  226,  224,  222,
      221,  220,  219,  218,  215,  214,  212,  207,  206,  205,
      204,  203,  201,  200,  199,  195,  193,  191,  190,  186,
      185,  184,  183,  181,  180,  179,  178,  177,  176,  174,
      173,  172,  171,  170,  168,  165,  163,  160,  158,  157,
      155,  154,  152,  151,  150,  149,  148,  145,  144,  143,
      142,  141,  140,  139,  138,  136,  135,  134,  132,  127,
      125,  124,  123,  122,  121,  120,  119,  116,  115,  114,

      113,  111,  110,  109,  107,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   96,   95,   94,   93,   92,   91,
       87,   86,   85,   83,   82,   81,   80,   79,   78,   77,
       76,   75,   74,   73,   71,   70,   69,   68,   67,   65,
       64,   63,   62,   61,   59,   58,   57,   56,   55,   54,
       53,   52,   51,   49,   41,   40,   39,   32,   31,   30,
       28,   27,   22,   21,   16,    8,    3,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
# line 1 "dbparser.l"
# line 2 "dbparser.l"
#define TOK_zero		0
#define TOK_inherit		1
#define TOK_pound		2
#define TOK_end			3
#define TOK_name		4
#define TOK_desc		5
#define TOK_sdesc		6
#define TOK_sect		7
#define TOK_zone		8
#define TOK_flags		9
#define TOK_type		10
#define TOK_exit		11
#define TOK_key			12
#define TOK_goto		13
#define TOK_dark		14
#define TOK_no_mob		15
#define TOK_indoors		16
#define TOK_no_fight		17
#define TOK_no_steal		18
#define TOK_no_summon		19
#define TOK_no_magic		20
#define TOK_private		21
#define TOK_sound1		22
#define TOK_sound2		23
#define TOK_isdoor		24
#define TOK_closed		25
#define TOK_locked		26
#define TOK_secret		27
#define TOK_trapped		28
#define TOK_pickproof		29
#define TOK_inside		30
#define TOK_city		31
#define TOK_field		32
#define TOK_forest		33
#define TOK_hills		34
#define TOK_mountain		35
#define TOK_swim		36
#define TOK_no_swim		37
#define TOK_air			38
#define TOK_underwater		39
#define TOK_north		40
#define TOK_east		41
#define TOK_south		42
#define TOK_west		43	
#define TOK_up			44
#define TOK_down		45
#define TOK_tilde		46
#define TOK_ID			47
#define TOK_cr			48
#define TOK_int			49
#define TOK_elof		50
#define TOK_tele_time		51
#define TOK_tele_targ		52
#define TOK_tele_look		53
#define TOK_no			54
#define TOK_yes			55
#define TOK_off			56
#define TOK_on			57
#define TOK_ex_desc		58

int ROOMcompile = 0;
int LINEcount = 1;
int NESTlevel = 0;
int MYtoken;

struct RET_flags {
  int TOKEN_type;
  int BIT_flag;
} GLOBAL_flags;


int LIST_sector[] = 
{ 
  TOK_inside,
  TOK_city,
  TOK_field,
  TOK_forest,
  TOK_hills,
  TOK_mountain,
  TOK_swim,
  TOK_no_swim,
  TOK_air,
  TOK_underwater,
  -1,
};

char * Sector_names[] = 
{
  "inside",
  "city",
  "field",
  "forest",
  "hills",
  "mountain",
  "swim",
  "no swim",
  "air",
  "underwater",
  0,
};

int LIST_water[] =
{
  TOK_swim,
  TOK_no_swim,
  TOK_air,
  TOK_underwater,
  -1,
};

int LIST_direction[] =
{
  TOK_north,
  TOK_east,
  TOK_south,
  TOK_west,
  TOK_up,
  TOK_down,
  -1,
};

int LIST_reply[] =
{
  TOK_yes,
  TOK_no,
  -1,
};

int LIST_exit_flags[] =
{
  TOK_isdoor,
  TOK_closed,
  TOK_locked,
  TOK_secret,
  TOK_trapped,
  TOK_pickproof,
  -1,
};

char * EXIT_FLAGS_NAMES[] = 
{
  "Isdoor",
  "Closed",
  "Locked",
  "Secret",
  "Trapped",
  "PickProof",
  "\n",
};
int EXIT_FLAGS[] = {1,2,4,8,16,32,-1};


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = getc( yyin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

# line 156 "dbparser.l"


	if ( yy_init )
		{
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( yy_current_buffer )
			yy_init_buffer( yy_current_buffer, yyin );
		else
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();

		yy_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 249 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 268 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_USER_ACTION
# line 157 "dbparser.l"
{ return(TOK_int); }
	YY_BREAK
case 2:
YY_USER_ACTION
# line 158 "dbparser.l"
{ printf("%s\n",yytext); }
	YY_BREAK
case 3:
YY_USER_ACTION
# line 159 "dbparser.l"
{ }
	YY_BREAK
case 4:
YY_USER_ACTION
# line 160 "dbparser.l"
{ return(TOK_inherit); }
	YY_BREAK
case 5:
YY_USER_ACTION
# line 161 "dbparser.l"
{ NESTlevel = 1;return(TOK_pound); }
	YY_BREAK
case 6:
YY_USER_ACTION
# line 162 "dbparser.l"
{ NESTlevel--;return(TOK_end); }
	YY_BREAK
case 7:
YY_USER_ACTION
# line 163 "dbparser.l"
{ return(TOK_name); }
	YY_BREAK
case 8:
YY_USER_ACTION
# line 164 "dbparser.l"
{ return(TOK_desc); }
	YY_BREAK
case 9:
YY_USER_ACTION
# line 165 "dbparser.l"
{ return(TOK_sdesc); }
	YY_BREAK
case 10:
YY_USER_ACTION
# line 166 "dbparser.l"
{ return(TOK_sect); }
	YY_BREAK
case 11:
YY_USER_ACTION
# line 167 "dbparser.l"
{ return(TOK_zone); }
	YY_BREAK
case 12:
YY_USER_ACTION
# line 168 "dbparser.l"
{ return(TOK_flags); }
	YY_BREAK
case 13:
YY_USER_ACTION
# line 169 "dbparser.l"
{ return(TOK_type); }
	YY_BREAK
case 14:
YY_USER_ACTION
# line 170 "dbparser.l"
{ NESTlevel++;return(TOK_exit); }
	YY_BREAK
case 15:
YY_USER_ACTION
# line 171 "dbparser.l"
{ return(TOK_key); }
	YY_BREAK
case 16:
YY_USER_ACTION
# line 172 "dbparser.l"
{ return(TOK_goto); }
	YY_BREAK
case 17:
YY_USER_ACTION
# line 173 "dbparser.l"
{ return(TOK_dark); }
	YY_BREAK
case 18:
YY_USER_ACTION
# line 174 "dbparser.l"
{ return(TOK_no_mob); }
	YY_BREAK
case 19:
YY_USER_ACTION
# line 175 "dbparser.l"
{ return(TOK_indoors); }
	YY_BREAK
case 20:
YY_USER_ACTION
# line 176 "dbparser.l"
{ return(TOK_no_fight); }
	YY_BREAK
case 21:
YY_USER_ACTION
# line 177 "dbparser.l"
{ return(TOK_no_steal); }
	YY_BREAK
case 22:
YY_USER_ACTION
# line 178 "dbparser.l"
{ return(TOK_no_summon) ; }
	YY_BREAK
case 23:
YY_USER_ACTION
# line 179 "dbparser.l"
{ return(TOK_no_magic); }
	YY_BREAK
case 24:
YY_USER_ACTION
# line 180 "dbparser.l"
{ return(TOK_private); }
	YY_BREAK
case 25:
YY_USER_ACTION
# line 181 "dbparser.l"
{ LINEcount++;return(TOK_sound1); }
	YY_BREAK
case 26:
YY_USER_ACTION
# line 182 "dbparser.l"
{ LINEcount++;return(TOK_sound2); }
	YY_BREAK
case 27:
YY_USER_ACTION
# line 183 "dbparser.l"
{ return(TOK_isdoor); }
	YY_BREAK
case 28:
YY_USER_ACTION
# line 184 "dbparser.l"
{ return(TOK_closed); }
	YY_BREAK
case 29:
YY_USER_ACTION
# line 185 "dbparser.l"
{ return(TOK_locked); }
	YY_BREAK
case 30:
YY_USER_ACTION
# line 186 "dbparser.l"
{ return(TOK_secret); }
	YY_BREAK
case 31:
YY_USER_ACTION
# line 187 "dbparser.l"
{ return(TOK_trapped); }
	YY_BREAK
case 32:
YY_USER_ACTION
# line 188 "dbparser.l"
{ return(TOK_pickproof); }
	YY_BREAK
case 33:
YY_USER_ACTION
# line 189 "dbparser.l"
{ return(TOK_inside); }
	YY_BREAK
case 34:
YY_USER_ACTION
# line 190 "dbparser.l"
{ return(TOK_city); }
	YY_BREAK
case 35:
YY_USER_ACTION
# line 191 "dbparser.l"
{ return(TOK_field); }
	YY_BREAK
case 36:
YY_USER_ACTION
# line 192 "dbparser.l"
{ return(TOK_forest); }
	YY_BREAK
case 37:
YY_USER_ACTION
# line 193 "dbparser.l"
{ return(TOK_hills); }
	YY_BREAK
case 38:
YY_USER_ACTION
# line 194 "dbparser.l"
{ return(TOK_mountain); }
	YY_BREAK
case 39:
YY_USER_ACTION
# line 195 "dbparser.l"
{ return(TOK_swim); }
	YY_BREAK
case 40:
YY_USER_ACTION
# line 196 "dbparser.l"
{ return(TOK_no_swim); }
	YY_BREAK
case 41:
YY_USER_ACTION
# line 197 "dbparser.l"
{ return(TOK_air); }
	YY_BREAK
case 42:
YY_USER_ACTION
# line 198 "dbparser.l"
{ return(TOK_underwater); }
	YY_BREAK
case 43:
YY_USER_ACTION
# line 199 "dbparser.l"
{ return(TOK_north); }
	YY_BREAK
case 44:
YY_USER_ACTION
# line 200 "dbparser.l"
{ return(TOK_south); }
	YY_BREAK
case 45:
YY_USER_ACTION
# line 201 "dbparser.l"
{ return(TOK_east); }
	YY_BREAK
case 46:
YY_USER_ACTION
# line 202 "dbparser.l"
{ return(TOK_west); }
	YY_BREAK
case 47:
YY_USER_ACTION
# line 203 "dbparser.l"
{ return(TOK_up); }
	YY_BREAK
case 48:
YY_USER_ACTION
# line 204 "dbparser.l"
{ return(TOK_down); }
	YY_BREAK
case 49:
YY_USER_ACTION
# line 205 "dbparser.l"
{ return(TOK_tilde); }
	YY_BREAK
case 50:
YY_USER_ACTION
# line 206 "dbparser.l"
{ return(TOK_elof); }
	YY_BREAK
case 51:
YY_USER_ACTION
# line 207 "dbparser.l"
{ return(TOK_tele_time); }
	YY_BREAK
case 52:
YY_USER_ACTION
# line 208 "dbparser.l"
{ return(TOK_tele_targ); }
	YY_BREAK
case 53:
YY_USER_ACTION
# line 209 "dbparser.l"
{ return(TOK_tele_look); }
	YY_BREAK
case 54:
YY_USER_ACTION
# line 210 "dbparser.l"
{ return(TOK_no); }
	YY_BREAK
case 55:
YY_USER_ACTION
# line 211 "dbparser.l"
{ return(TOK_yes); }
	YY_BREAK
case 56:
YY_USER_ACTION
# line 212 "dbparser.l"
{ return(TOK_off); }
	YY_BREAK
case 57:
YY_USER_ACTION
# line 213 "dbparser.l"
{ return(TOK_on); }
	YY_BREAK
case 58:
YY_USER_ACTION
# line 214 "dbparser.l"
{ return(TOK_ex_desc); }
	YY_BREAK
case 59:
YY_USER_ACTION
# line 215 "dbparser.l"
{ return(TOK_ID); }
	YY_BREAK
case 60:
YY_USER_ACTION
# line 216 "dbparser.l"
{ LINEcount++;}  
	YY_BREAK
case 61:
YY_USER_ACTION
# line 217 "dbparser.l"
{ }
	YY_BREAK
case 62:
YY_USER_ACTION
# line 218 "dbparser.l"
{ }
	YY_BREAK
case 63:
YY_USER_ACTION
# line 219 "dbparser.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = yy_cp - yytext_ptr - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
							yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = yy_c_buf_p - yytext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset = yy_c_buf_p - b->yy_ch_buf;

			b->yy_buf_size *= 2;
			b->yy_ch_buf = (char *)
				yy_flex_realloc( (void *) b->yy_ch_buf,
						 b->yy_buf_size );

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move - YY_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	/* yytext begins at the second character in yy_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * yy_get_previous_state() will have with '^' rules active.
	 */

	yytext_ptr = &yy_current_buffer->yy_ch_buf[1];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 249 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 249 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 248);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += dest - source;
		yy_bp += dest - source;
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
		yy_cp[-2] = '\n';

	*--yy_cp = (char) c;


	/* Note: the formal parameter *must* be called "yy_bp" for this
	 * macro to now work correctly.
	 */
	YY_DO_BEFORE_ACTION; /* set up yytext again */
	}


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );

	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );

	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	yy_flex_free( (void *) b->yy_ch_buf );
	yy_flex_free( (void *) b );
	}


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->yy_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->yy_ch_buf[0] = '\n';
	b->yy_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[1];

	b->yy_is_interactive = file ? isatty( fileno(file) ) : 0;

	b->yy_fill_buffer = 1;

	b->yy_buffer_status = YY_BUFFER_NEW;
	}


#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		int new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}


static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}


static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}


#ifdef YY_USE_PROTOS
static void yy_fatal_error( const char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, const char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
const char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( unsigned int size )
#else
static void *yy_flex_alloc( size )
unsigned int size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, unsigned int size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
unsigned int size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}
# line 219 "dbparser.l"

